[features]
seeds = false
[programs.localnet]
solana_twitter = "Cmx8tcBfPpmv6vJ1sqonPTHESYJpnTSgS8K7DD1TfpfM"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/flygon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
